name: ecg_cnn_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - cudatoolkit=11.8      # remove if CPU-only
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - shap>=0.45
  - streamlit>=1.30
  - wfdb
  - tqdm
  - jupytext
  - jupyter
  - ipykernel
  - pip
  - pip:
      - -e .[dev]
      - pytest
      - pytest-cov
      - coverage
