name: ecg_cnn_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8        # Optional: remove if CPU-only
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - ipykernel
  - seaborn
  - pip
  - pip:
      - -e ./
      - wfdb
      - tqdm
      - jupytext
      - pytest
      - pytest-cov
