model: ECGConvNet

# Training hyperparameters
lr: 0.001
batch_size: 64
weight_decay: 0.0
epochs: 10
save_best: true

# Data loading
sample_only: false
subsample_frac: 1.0
sampling_rate: 100
data_dir: null     # optional override
sample_dir: null   # optional override