model: [ECGInceptionNet, ECGResNet, ECGConvNet]   # Name of the model classes (must match a model in
                                                  # models/model_utils.py)

# ------------------------------------------------------------------------------
# Training Hyperparameters
# ------------------------------------------------------------------------------
lr: [0.001, 0.0005, 0.0001]        # Learning rate for optimizer (e.g., Adam)
batch_size: [64]                   # Number of samples per gradient update
weight_decay: [0.0, 0.0005]        # L2 regularization strength
n_epochs: 50                       # Total number of training epochs
save_best: true                    # If true, save the model with the lowest
                                   #   val loss, otherwise, don't save the 
                                   #   model

# ------------------------------------------------------------------------------
# Data Loading
# ------------------------------------------------------------------------------
sample_only: false   # If true, load a small sample (for testing/debug)
subsample_frac: 1.0  # Fraction of the full dataset to use (1.0 = all data)
sampling_rate: 100   # ECG resampling rate in Hz (100 or 500)
data_dir: null       # Optional override for PTB-XL dataset directory
sample_dir: null     # Optional override for sample data location

# ------------------------------------------------------------------------------
# Control Plotting in evaluate.py
# ------------------------------------------------------------------------------
plots_enable_ovr: false
#plots_ovr_classes: null #[]

# ------------------------------------------------------------------------------
# Housekeeping
# ------------------------------------------------------------------------------
n_folds: 5           # Number of folds to use for cross-validation (e.g., 5 for 
                     #   5-fold CV).
verbose: true        # Print config summary and training details
